[theme]
base = "light"
primaryColor = "#8E735B"
backgroundColor = "#F2EFE9"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#3A3228"

[server]
headless = true
enableCORS = false
enableXsrfProtection = false
